version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: f1pa_postgres
    environment:
      POSTGRES_USER: f1pa
      POSTGRES_PASSWORD: f1pa
      POSTGRES_DB: f1pa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: f1pa_mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns

volumes:
  postgres_data:
