version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: f1pa_postgres
    environment:
      POSTGRES_USER: f1pa
      POSTGRES_PASSWORD: f1pa
      POSTGRES_DB: f1pa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.8.0
    container_name: f1pa_mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root mlflow-artifacts:
      --artifacts-destination /mlartifacts
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --allowed-hosts "*"
    ports:
      - "5000:5000"
    volumes:
      - ./mlartifacts:/mlartifacts
      - ./mlflow_db:/mlflow
    working_dir: /

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: f1pa_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=f1pa_db
      - POSTGRES_USER=f1pa
      - POSTGRES_PASSWORD=f1pa
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=F1PA_LapTime_Prediction
      - DEFAULT_MODEL_FAMILY=auto
      - DEFAULT_MODEL_STRATEGY=mae
    depends_on:
      - postgres
      - mlflow
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./monitoring/evidently/reports:/app/monitoring/evidently/reports

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: f1pa_streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
      - API_USERNAME=f1pa
      - API_PASSWORD=f1pa
      - MLFLOW_URL=http://localhost:5000
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: f1pa_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.5.0
    container_name: f1pa_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
