version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: f1pa_postgres
    environment:
      POSTGRES_USER: f1pa
      POSTGRES_PASSWORD: f1pa
      POSTGRES_DB: f1pa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.8.0
    container_name: f1pa_mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root mlflow-artifacts:
      --artifacts-destination /mlartifacts
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
    ports:
      - "5000:5000"
    volumes:
      - ./mlartifacts:/mlartifacts
      - ./mlflow_db:/mlflow
    working_dir: /

volumes:
  postgres_data:
